
import './globals.css'
import { Inter } from 'next/font/google'
import { CategoryContext } from '../hooks/useCategory';
import { useContext } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Meal DB',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CategoryContext>
      <body className={inter.className}>
        {children}
      </body>
      </CategoryContext>
      
    </html>
  )
}
